apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busy
    command: ['sh','-c','while true; do sleep 3600; done']
  - image: nginx:1.19.2
    name: web

