apiVersion: v1
kind: Pod
metadata:
  name: init-contianer-pod
spec:
  initContainers:
  - name: delay
    image: busybox
    command: ['sh','-c','sleep 30; echo delay init done with sucess']
  - name: prepare-web
    image: alpine:3.22.2
    command: ['sh','-c','apk update; apk add git; git clone -b develop https://github.com/mariano-italiano/kubernetes-sm2.git /data']
    volumeMounts:
    - name: sharedvol
      mountPath: /data
  containers:
  - name: web
    image: nginx
    volumeMounts:
    - name: sharedvol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: sharedvol
    emptyDir: {}
